import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/src/styles/globals.css';
import QueryProvider from '@/src/utils/QueryProvider';
import FooterBar from '../components/common/footerBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'DapJi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <QueryProvider>
          {children}
          <FooterBar />
        </QueryProvider>
      </body>
    </html>
  );
}
