export type ClimbLIstType = {
  gym_id?: number;
  name: string;
  adress?: string;
  logo: any;
  notice?: string | null;
};

export const climbLists = [
  {
    gym_id: 1,
    name: '락랜드',
    adress: '서울특별시 강북구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcCa4na%2FbtsIMxBjSX8%2Fmy6IojkItzLjKZ1WoWAIzK%2Fimg.jpg',
    notice: '8월 30일부터 다음셋팅입니다',
  },
  {
    gym_id: 2,
    name: '클라이밍월드',
    adress: '서울특별시 종로구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FYptzI%2FbtsIMCWFQ9C%2FA38QkNnQQ1KePj7K0ZtWz0%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 3,
    name: '볼더파크',
    adress: '서울특별시 용산구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FwLygU%2FbtsINu4VkwW%2FWdNfcOvdzGXNIiOmq1qIpk%2Fimg.jpg',
    notice: '9월 5일 신규 루트 세팅 예정',
  },
  {
    gym_id: 4,
    name: '클라임존',
    adress: '서울특별시 서대문구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2F8t6sg%2FbtsIOoJCGoE%2FVoXB0BL7tKW7N0NOUXXtGK%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 5,
    name: '알피니스트',
    adress: '서울특별시 강남구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '10월 1일부터 대회 준비로 인해 일시 휴업',
  },
  {
    gym_id: 6,
    name: '클라임스페이스',
    adress: '서울특별시 마포구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 7,
    name: '볼더랜드',
    adress: '서울특별시 성북구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '8월 25일 새로운 회원 모집',
  },
  {
    gym_id: 8,
    name: '클라이머즈',
    adress: '서울특별시 은평구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 9,
    name: '클라이밍하우스',
    adress: '서울특별시 강서구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '9월 10일 이벤트 공지 예정',
  },
  {
    gym_id: 10,
    name: '락하우스',
    adress: '서울특별시 동대문구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 11,
    name: '클라이밍아레나',
    adress: '서울특별시 중랑구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '8월 20일부터 신규 루트 오픈',
  },
  {
    gym_id: 12,
    name: '클라임파크',
    adress: '서울특별시 노원구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 13,
    name: '볼더짐',
    adress: '서울특별시 구로구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '9월 1일 클라이밍 강좌 개설',
  },
  {
    gym_id: 14,
    name: '클라이밍랜드',
    adress: '서울특별시 금천구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 15,
    name: '클라임업',
    adress: '서울특별시 영등포구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '10월 5일부터 운영 시간 변경',
  },
  {
    gym_id: 16,
    name: '볼더클럽',
    adress: '서울특별시 양천구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 17,
    name: '클라이밍펀',
    adress: '서울특별시 도봉구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '8월 15일 회원 이벤트',
  },
  {
    gym_id: 18,
    name: '락펀',
    adress: '서울특별시 동작구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 19,
    name: '클라임아카데미',
    adress: '서울특별시 관악구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: '9월 20일부터 강습 시작',
  },
  {
    gym_id: 20,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 21,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 22,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 23,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 24,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 25,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 26,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 27,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 28,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 29,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },
  {
    gym_id: 230,
    name: '클라임챌린지',
    adress: '서울특별시 서초구 ',
    logo: 'https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbrpH7d%2FbtsIMFlyHDh%2FTnaklhHTWwWevnmrDRvPjk%2Fimg.jpg',
    notice: null,
  },

];
